//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitirmeProjem.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public string ModifyUsername { get; set; }
        public Nullable<int> PostId { get; set; }
        public Nullable<int> SocialMediaUser_Id { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual SocialMediaUser SocialMediaUser { get; set; }
    }
}
